### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MarvelGa** [MarvelGa/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by evgen8888** [comment]
- I am the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney - I have a Gucci strore that's worth more then Romney. Sorry losers nad haters, but my IQ is one of the highest - and you all know it! Please don't feel so stupid or insecure, it's not your fault.

**Comment by MarvelGa** [comment]
> * I am the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney - I have a Gucci strore that's worth more then Romney. Sorry losers nad haters, but my IQ is one of the highest - and you all know it! Please don't feel so stupid or insecure, it's not your fault.

**Comment by MarvelGa** [comment]
thanks.

**Comment by evgen8888** [comment]
<h2>Résumé</h2>
<p>&mdash; I am the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney - I have a Gucci strore that's worth more then Romney. Sorry losers nad haters, but my IQ is one of the highest - and you all know it! Please don't feel so stupid or insecure, it's not your fault.<p>
